# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdevTutorial',
                'doc_host': 'https://dice43.github.io',
                'git_url': 'https://github.com/dice43/nbdevTutorial',
                'lib_path': 'nbdevTutorial'},
  'syms': {'nbdevTutorial.core': {'nbdevTutorial.core.foo': ('core.html#foo', 'nbdevTutorial/core.py')}}}
